const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='torti-v1-data';const PHOTO='torti-v1-photo';
const state=JSON.parse(localStorage.getItem(KEY)||'{"records":[],"checks":{}}');let currentType='peso';let currentFilter='all';
const configs={
 peso:{title:'Peso y medidas',icon:'⚖️',fields:`<div class="form-grid"><label>Peso (g)<input name="weight" type="number" min="1" step="1" placeholder="Ej. 1350" required></label><label>Largo caparazón (cm)<input name="length" type="number" min="1" step="0.1" placeholder="Ej. 19.5"></label></div><label>Ancho caparazón (cm)<input name="width" type="number" min="1" step="0.1" placeholder="Opcional"></label>`},
 comida:{title:'Alimentación',icon:'🥬',fields:`<label>¿Qué comió?<input name="food" required placeholder="Ej. escarola, zapallo, hojas..."></label><div class="form-grid"><label>Cantidad aproximada<input name="amount" placeholder="Ej. 1 taza"></label><label>Apetito<select name="appetite"><option>Bueno</option><option>Regular</option><option>Bajo</option><option>No comió</option></select></label></div>`},
 salud:{title:'Control de salud',icon:'❤️',fields:`<div class="form-grid"><label>Actividad<select name="activity"><option>Normal</option><option>Muy activa</option><option>Baja</option><option>Letárgica</option></select></label><label>Ojos y nariz<select name="eyes"><option>Normales</option><option>Ojos alterados</option><option>Secreción nasal</option></select></label></div><div class="form-grid"><label>Caparazón<select name="shell"><option>Sin cambios</option><option>Con cambio visible</option><option>Lesión</option></select></label><label>Heces<select name="stool"><option>Normales</option><option>Diferentes</option><option>Sin observar</option></select></label></div>`},
 habitat:{title:'Hábitat',icon:'🌡️',fields:`<div class="form-grid"><label>Temperatura (°C)<input name="temp" type="number" step="0.1" placeholder="Ej. 28"></label><label>Humedad (%)<input name="humidity" type="number" min="0" max="100" placeholder="Ej. 80"></label></div><div class="form-grid"><label>UVB / luz<select name="uvb"><option>Revisado</option><option>No revisado</option><option>Requiere cambio</option></select></label><label>Limpieza<select name="clean"><option>Correcta</option><option>Pendiente</option><option>Realizada hoy</option></select></label></div>`},
 veterinario:{title:'Veterinario',icon:'🩺',fields:`<label>Motivo / consulta<input name="reason" required placeholder="Control, análisis, tratamiento..."></label><label>Veterinario o clínica<input name="vet" placeholder="Opcional"></label><label>Próxima cita<input name="next" type="date"></label>`},
 recuerdo:{title:'Nuevo recuerdo',icon:'📸',fields:`<label>Título del recuerdo<input name="memory" required placeholder="Ej. Su primer baño del mes"></label><label>Descripción<input name="description" placeholder="Un momento especial con Torti"></label>`}
};
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function fmtDate(s){if(!s)return'';const [y,m,d]=s.split('-').map(Number);return new Intl.DateTimeFormat('es-PE',{day:'numeric',month:'short',year:'numeric'}).format(new Date(Date.UTC(y,m-1,d)))}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function typeLabel(t){return configs[t]?.title||t}
function summary(r){const v=r.data;switch(r.type){case'peso':return `${v.weight} g${v.length?` · ${v.length} cm`:''}`;case'comida':return `${v.food}${v.appetite?` · apetito ${v.appetite.toLowerCase()}`:''}`;case'salud':return `${v.activity||'Control'} · ${v.eyes||''}`;case'habitat':return `${v.temp?`${v.temp} °C`:''}${v.humidity?` · ${v.humidity}% humedad`:''}`||'Hábitat revisado';case'veterinario':return v.reason||'Consulta veterinaria';case'recuerdo':return v.memory||'Recuerdo';default:return r.notes||''}}
function renderList(el,records){if(!records.length){el.className='timeline empty';el.textContent='Todavía no hay registros.';return}el.className='timeline';el.innerHTML=records.map(r=>`<article class="entry"><div class="icon">${configs[r.type]?.icon||'•'}</div><div><b>${typeLabel(r.type)}</b><small>${escapeHtml(summary(r))}${r.notes?`<br>${escapeHtml(r.notes)}`:''}</small></div><time>${fmtDate(r.date)}</time></article>`).join('')}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){const rec=[...state.records].sort((a,b)=>b.date.localeCompare(a.date)||b.created-a.created);renderList($('#recentList'),rec.slice(0,4));const filtered=currentFilter==='all'?rec:rec.filter(r=>r.type===currentFilter);renderList($('#historyList'),filtered);$('#statCount').textContent=state.records.length;$('#statMemories').textContent=state.records.filter(r=>r.type==='recuerdo').length;const weights=rec.filter(r=>r.type==='peso');$('#statWeight').textContent=weights[0]?`${weights[0].data.weight} g`:'—';$('#lastWeight').textContent=weights[0]?`${weights[0].data.weight} g`:'Pendiente';const food=rec.find(r=>r.type==='comida');$('#lastFood').textContent=food?food.data.food:'Sin registro';const health=rec.find(r=>r.type==='salud');$('#lastHealth').textContent=health?health.data.activity:'Sin revisión';const habitat=rec.find(r=>r.type==='habitat');$('#lastHabitat').textContent=habitat?'Registrado':'Por revisar';$('#heroSummary').textContent=weights[0]?`Último peso: ${weights[0].data.weight} g. Sigue registrando pequeños cambios para ver su evolución.`:'Registra su primera medición para comenzar su historial.';$$('[data-check]').forEach(x=>x.checked=!!state.checks[`${today()}-${x.dataset.check}`]);const done=$$('[data-check]').filter(x=>x.checked).length;$('#checkProgress').textContent=`${done}/4`}
function nav(name){$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$$('.tabbar [data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));scrollTo({top:0,behavior:'smooth'})}
function openRecord(type){currentType=type;const c=configs[type];$('#dialogTitle').textContent=c.title;$('#dynamicFields').innerHTML=c.fields;$('#recordDate').value=today();$('#recordForm').reset();$('#recordDate').value=today();$('#recordDialog').showModal()}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openRecord(b.dataset.open)));$('#closeDialog').addEventListener('click',()=>$('#recordDialog').close());
$('#recordForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={};for(const [k,v] of fd.entries())if(!['date','notes'].includes(k)&&v!=='')data[k]=v;state.records.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),type:currentType,date:fd.get('date'),notes:fd.get('notes')||'',data,created:Date.now()});save();$('#recordDialog').close();toast('Registro guardado 💛');nav('inicio')});
$$('[data-check]').forEach(c=>c.addEventListener('change',()=>{state.checks[`${today()}-${c.dataset.check}`]=c.checked;save()}));
$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;currentFilter=b.dataset.filter;$$('#filters button').forEach(x=>x.classList.toggle('active',x===b));render()});
function setPhoto(src){localStorage.setItem(PHOTO,src);applyPhoto(src)}function applyPhoto(src){if(!src)return;$('#heroPhoto').innerHTML=`<img src="${src}" alt="Foto de Torti">`;$('#profilePhoto').innerHTML=`<img src="${src}" alt="Foto de Torti">`;$('#photoBtn').innerHTML=`<img src="${src}" alt="Foto de Torti">`}
$('#photoBtn').addEventListener('click',()=>$('#photoInput').click());$('#photoInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(f.size>3_000_000){toast('Usa una foto menor de 3 MB');return}const rd=new FileReader();rd.onload=()=>setPhoto(rd.result);rd.readAsDataURL(f)});
$('#exportBtn').addEventListener('click',()=>{const payload={version:1,exported:new Date().toISOString(),state,photo:localStorage.getItem(PHOTO)||null};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`torti-respaldo-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Respaldo creado')});
$('#importBtn').addEventListener('click',()=>$('#importInput').click());$('#importInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!p.state||!Array.isArray(p.state.records))throw 0;state.records=p.state.records;state.checks=p.state.checks||{};if(p.photo)setPhoto(p.photo);save();toast('Respaldo restaurado')}catch{toast('Ese archivo no es un respaldo válido')}};r.readAsText(f)});
$('#clearBtn').addEventListener('click',()=>{if(confirm('¿Borrar todos los registros de Torti de este dispositivo?')){state.records=[];state.checks={};localStorage.removeItem(KEY);render();toast('Datos eliminados')}});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
applyPhoto(localStorage.getItem(PHOTO));render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});