const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='torti-v1-data',PHOTO='torti-v1-photo',THEME='torti-theme';
const state=JSON.parse(localStorage.getItem(KEY)||'{"records":[],"checks":{},"tasks":[]}');
state.records=Array.isArray(state.records)?state.records:[];state.checks=state.checks||{};state.tasks=Array.isArray(state.tasks)?state.tasks:[];
let currentType='peso',currentFilter='all',taskFilter='pending';
const configs={
 peso:{title:'Peso y medidas',icon:'⚖️',fields:`<div class="form-grid"><label>Peso (g)<input name="weight" type="number" min="1" step="1" placeholder="Ej. 1350" required></label><label>Largo caparazón (cm)<input name="length" type="number" min="1" step="0.1" placeholder="Ej. 19.5"></label></div><label>Ancho caparazón (cm)<input name="width" type="number" min="1" step="0.1" placeholder="Opcional"></label>`},
 comida:{title:'Alimentación',icon:'🥬',fields:`<label>¿Qué comió?<input name="food" required placeholder="Ej. hojas, flores, verduras..."></label><div class="form-grid"><label>Cantidad aproximada<input name="amount" placeholder="Ej. 1 taza"></label><label>Apetito<select name="appetite"><option>Bueno</option><option>Regular</option><option>Bajo</option><option>No comió</option></select></label></div>`},
 salud:{title:'Control de salud',icon:'❤️',fields:`<div class="form-grid"><label>Actividad<select name="activity"><option>Normal</option><option>Muy activa</option><option>Baja</option><option>Letárgica</option></select></label><label>Ojos y nariz<select name="eyes"><option>Normales</option><option>Ojos alterados</option><option>Secreción nasal</option></select></label></div><div class="form-grid"><label>Caparazón<select name="shell"><option>Sin cambios</option><option>Con cambio visible</option><option>Lesión</option></select></label><label>Heces<select name="stool"><option>Normales</option><option>Diferentes</option><option>Sin observar</option></select></label></div>`},
 habitat:{title:'Hábitat',icon:'🌡️',fields:`<div class="form-grid"><label>Temperatura (°C)<input name="temp" type="number" step="0.1" placeholder="Ej. 28"></label><label>Humedad (%)<input name="humidity" type="number" min="0" max="100" placeholder="Ej. 80"></label></div><div class="form-grid"><label>UVB / luz<select name="uvb"><option>Revisado</option><option>No revisado</option><option>Requiere cambio</option></select></label><label>Limpieza<select name="clean"><option>Correcta</option><option>Pendiente</option><option>Realizada hoy</option></select></label></div>`},
 veterinario:{title:'Veterinario',icon:'🩺',fields:`<label>Motivo / consulta<input name="reason" required placeholder="Control, análisis, tratamiento..."></label><label>Veterinario o clínica<input name="vet" placeholder="Opcional"></label><label>Próxima cita<input name="next" type="date"></label>`},
 recuerdo:{title:'Nuevo recuerdo',icon:'📸',fields:`<label>Título del recuerdo<input name="memory" required placeholder="Ej. Día de fresitas"></label><label>Foto<input name="photoFile" type="file" accept="image/*"></label><label>Descripción<input name="description" placeholder="Un momento especial con Torti"></label>`}
};
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function uid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmtDate(s){if(!s)return'';const [y,m,d]=s.split('-').map(Number);return new Intl.DateTimeFormat('es-PE',{day:'numeric',month:'short',year:'numeric'}).format(new Date(Date.UTC(y,m-1,d)))}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function typeLabel(t){return configs[t]?.title||t}
function summary(r){const v=r.data||{};switch(r.type){case'peso':return `${v.weight||'—'} g${v.length?` · ${v.length} cm`:''}`;case'comida':return `${v.food||'Comida'}${v.appetite?` · apetito ${v.appetite.toLowerCase()}`:''}`;case'salud':return `${v.activity||'Control'} · ${v.eyes||''}`;case'habitat':return `${v.temp?`${v.temp} °C`:''}${v.humidity?` · ${v.humidity}% humedad`:''}`||'Hábitat revisado';case'veterinario':return v.reason||'Consulta veterinaria';case'recuerdo':return v.memory||'Recuerdo';default:return r.notes||''}}
function sortedRecords(){return [...state.records].sort((a,b)=>b.date.localeCompare(a.date)||b.created-a.created)}
function renderList(el,records){if(!records.length){el.className='timeline empty';el.textContent='Todavía no hay registros.';return}el.className='timeline';el.innerHTML=records.map(r=>`<article class="entry"><div class="icon">${configs[r.type]?.icon||'•'}</div><div><b>${escapeHtml(typeLabel(r.type))}</b><small>${escapeHtml(summary(r))}${r.notes?`<br>${escapeHtml(r.notes)}`:''}</small></div><time>${fmtDate(r.date)}</time><div class="entry-actions"><button data-delete-record="${r.id}">Eliminar</button></div></article>`).join('')}
function getAlerts(){const rec=sortedRecords(),alerts=[];const h=rec.find(r=>r.type==='salud');if(h){const d=h.data||{};if(['Baja','Letárgica'].includes(d.activity))alerts.push('Actividad baja registrada. Si persiste o empeora, consulta a un veterinario de reptiles.');if(d.eyes&&d.eyes!=='Normales')alerts.push(`${d.eyes} registrado. Vigílalo y consulta si persiste.`);if(d.shell&&d.shell!=='Sin cambios')alerts.push(`${d.shell} en caparazón. Documenta con fotos y considera revisión veterinaria.`)}const f=rec.find(r=>r.type==='comida');if(f&&['Bajo','No comió'].includes(f.data?.appetite))alerts.push(`Apetito ${String(f.data.appetite).toLowerCase()} en el último registro. Observa tendencia y otros cambios.`);const w=rec.filter(r=>r.type==='peso').slice(0,2);if(w.length===2){const a=Number(w[0].data.weight),b=Number(w[1].data.weight);if(a>0&&b>0&&a<b*.9)alerts.push('El último peso bajó más de 10% respecto al registro anterior. Repite la medición y consulta si se confirma.')}return alerts}
function smartRecommendation(){const rec=sortedRecords();if(!rec.length)return 'Registra hoy su peso, alimentación o hábitat para empezar a construir tendencias útiles.';const dates={};for(const r of rec)if(!dates[r.type])dates[r.type]=r.date;const days=s=>Math.floor((new Date(today()+'T12:00:00')-new Date(s+'T12:00:00'))/86400000);if(!dates.peso||days(dates.peso)>30)return 'Hace tiempo que no registras su peso. Una medición consistente te ayudará a ver cambios reales en el tiempo.';if(!dates.salud||days(dates.salud)>7)return 'Haz un chequeo visual esta semana: actividad, ojos, nariz, caparazón y heces.';if(!dates.habitat||days(dates.habitat)>7)return 'Actualiza el hábitat: temperatura, humedad, UVB y limpieza. Mantén como referencia los objetivos indicados por su veterinario de reptiles.';if(!dates.comida||days(dates.comida)>3)return 'Registra algunas comidas esta semana para reconocer preferencias y cambios de apetito.';return 'Vas llevando un seguimiento constante. Mantén los registros con la misma balanza y de forma similar para comparar mejor.'}
function growthChart(weights){const el=$('#growthChart');if(weights.length<2){el.className='chart-empty';el.textContent='Añade al menos 2 mediciones para ver la gráfica.';return}const pts=[...weights].reverse().slice(-12),vals=pts.map(r=>Number(r.data.weight)).filter(Number.isFinite);const min=Math.min(...vals),max=Math.max(...vals),range=Math.max(max-min,1),W=600,H=240,pad=34;const coords=pts.map((r,i)=>{const x=pad+i*(W-pad*2)/Math.max(pts.length-1,1),y=H-pad-(Number(r.data.weight)-min)*(H-pad*2)/range;return{x,y,r}});const line=coords.map(p=>`${p.x},${p.y}`).join(' ');el.className='chart-wrap';el.innerHTML=`<svg class="chart-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="Evolución del peso de Torti"><line class="chart-grid" x1="${pad}" y1="${pad}" x2="${pad}" y2="${H-pad}"/><line class="chart-grid" x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}"/><polyline class="chart-line" points="${line}"/>${coords.map((p,i)=>`<circle class="chart-dot" cx="${p.x}" cy="${p.y}" r="6"><title>${fmtDate(p.r.date)}: ${p.r.data.weight} g</title></circle>${i===0||i===coords.length-1?`<text class="chart-label" x="${p.x}" y="${H-8}" text-anchor="middle">${escapeHtml(p.r.date.slice(5))}</text>`:''}`).join('')}<text class="chart-label" x="${pad+4}" y="${pad+2}">${Math.round(max)} g</text><text class="chart-label" x="${pad+4}" y="${H-pad-6}">${Math.round(min)} g</text></svg>`}
function renderTasks(){const list=$('#taskList'),items=[...state.tasks].sort((a,b)=>a.date.localeCompare(b.date)).filter(t=>taskFilter==='done'?t.done:!t.done);if(!items.length){list.innerHTML='<p class="muted">No hay tareas en esta sección.</p>';return}list.innerHTML=items.map(t=>`<div class="task-row ${t.done?'done':''}"><input type="checkbox" data-task-toggle="${t.id}" ${t.done?'checked':''} aria-label="Completar tarea"><div><b>${escapeHtml(t.title)}</b><small>${escapeHtml(t.category)} · ${fmtDate(t.date)}</small></div><button class="trash" data-task-delete="${t.id}" aria-label="Eliminar tarea">×</button></div>`).join('')}
function renderAlbum(){const memories=sortedRecords().filter(r=>r.type==='recuerdo');const el=$('#albumGrid');if(!memories.length){el.innerHTML='<p class="muted">Aún no hay recuerdos.</p>';return}el.innerHTML=memories.map(r=>`<article class="album-card">${r.data?.photo?`<img src="${r.data.photo}" alt="${escapeHtml(r.data.memory||'Recuerdo de Torti')}">`:`<div class="album-placeholder">🐢</div>`}<div class="caption"><b>${escapeHtml(r.data?.memory||'Recuerdo')}</b><small>${fmtDate(r.date)}</small></div></article>`).join('')}
function render(){const rec=sortedRecords();renderList($('#recentList'),rec.slice(0,4));renderList($('#historyList'),currentFilter==='all'?rec:rec.filter(r=>r.type===currentFilter));$('#statCount').textContent=state.records.length;$('#statMemories').textContent=state.records.filter(r=>r.type==='recuerdo').length;$('#statTasks').textContent=state.tasks.filter(t=>!t.done).length;const weights=rec.filter(r=>r.type==='peso');const latest=weights[0];$('#lastWeight').textContent=latest?`${latest.data.weight} g`:'Pendiente';$('#growthWeight').textContent=latest?`${latest.data.weight} g`:'—';$('#growthCount').textContent=weights.length;$('#growthDelta').textContent=weights.length>1?`${Number(weights[0].data.weight)-Number(weights[1].data.weight)>0?'+':''}${Number(weights[0].data.weight)-Number(weights[1].data.weight)} g`:'—';growthChart(weights);$('#measureList').innerHTML=weights.length?weights.slice(0,5).map(r=>`<div class="mini-item"><div><b>${fmtDate(r.date)}</b><small>${r.data.length?`Largo ${escapeHtml(r.data.length)} cm`:''}${r.data.width?` · ancho ${escapeHtml(r.data.width)} cm`:''}</small></div><strong>${escapeHtml(r.data.weight)} g</strong></div>`).join(''):'<p class="muted">Sin mediciones todavía.</p>';const food=rec.find(r=>r.type==='comida'),health=rec.find(r=>r.type==='salud'),habitat=rec.find(r=>r.type==='habitat');$('#lastFood').textContent=food?food.data.food:'Sin registro';$('#lastHealth').textContent=health?health.data.activity:'Sin revisión';$('#lastHabitat').textContent=habitat?(habitat.data.temp?`${habitat.data.temp} °C`:'Registrado'):'Por revisar';$('#heroSummary').textContent=latest?`Último peso: ${latest.data.weight} g · ${state.records.length} registros guardados.`:'Empieza con su primera medición.';$('#smartRecommendation').textContent=smartRecommendation();const alerts=getAlerts();$('#alertCount').textContent=alerts.length;$('#alertsList').innerHTML=alerts.length?alerts.map(a=>`<div class="alert-item">${escapeHtml(a)}</div>`).join(''):'<p class="muted">Sin alertas registradas.</p>';$$('[data-check]').forEach(x=>x.checked=!!state.checks[`${today()}-${x.dataset.check}`]);$('#checkProgress').textContent=`${$$('[data-check]').filter(x=>x.checked).length}/4`;const upcoming=[...state.tasks].filter(t=>!t.done&&t.date>=today()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3);$('#upcomingTasks').innerHTML=upcoming.length?upcoming.map(t=>`<div class="mini-item"><div><b>${escapeHtml(t.title)}</b><small>${escapeHtml(t.category)}</small></div><strong>${fmtDate(t.date)}</strong></div>`).join(''):'<p class="muted">No hay tareas pendientes.</p>';renderTasks();renderAlbum()}
function nav(name){$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$$('.tabbar [data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='album')renderAlbum()}
function openRecord(type){currentType=type;const c=configs[type];$('#dialogTitle').textContent=c.title;$('#dynamicFields').innerHTML=c.fields;$('#recordForm').reset();$('#recordDate').value=today();$('#recordDialog').showModal()}
async function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.72))};img.onerror=reject;img.src=url})}
function applyPhoto(src){const use=src||$('#defaultPhoto').src;['#heroPhoto','#profilePhoto','#photoBtn'].forEach(sel=>$(sel).innerHTML=`<img src="${use}" alt="Foto de Torti">`)}
function setPhoto(src){localStorage.setItem(PHOTO,src);applyPhoto(src)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openRecord(b.dataset.open)));$('#closeDialog').addEventListener('click',()=>$('#recordDialog').close());
$('#recordForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={};for(const [k,v] of fd.entries())if(!['date','notes','photoFile'].includes(k)&&v!=='')data[k]=v;const f=fd.get('photoFile');if(f instanceof File&&f.size){try{data.photo=await compressImage(f)}catch{toast('No pude procesar esa foto')}}state.records.push({id:uid(),type:currentType,date:fd.get('date'),notes:fd.get('notes')||'',data,created:Date.now()});save();$('#recordDialog').close();toast('Registro guardado 💛');nav(currentType==='recuerdo'?'album':'inicio')});
$$('[data-check]').forEach(c=>c.addEventListener('change',()=>{state.checks[`${today()}-${c.dataset.check}`]=c.checked;save()}));
$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;currentFilter=b.dataset.filter;$$('#filters button').forEach(x=>x.classList.toggle('active',x===b));render()});
document.addEventListener('click',e=>{const del=e.target.closest('[data-delete-record]');if(del&&confirm('¿Eliminar este registro?')){state.records=state.records.filter(r=>r.id!==del.dataset.deleteRecord);save()}const tog=e.target.closest('[data-task-toggle]');if(tog){const t=state.tasks.find(x=>x.id===tog.dataset.taskToggle);if(t){t.done=tog.checked;save()}}const td=e.target.closest('[data-task-delete]');if(td){state.tasks=state.tasks.filter(t=>t.id!==td.dataset.taskDelete);save()}});
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);state.tasks.push({id:uid(),title:fd.get('title'),date:fd.get('date'),category:fd.get('category'),done:false,created:Date.now()});e.currentTarget.reset();save();toast('Tarea agregada')});
$('#taskTabs').addEventListener('click',e=>{const b=e.target.closest('[data-taskfilter]');if(!b)return;taskFilter=b.dataset.taskfilter;$$('#taskTabs button').forEach(x=>x.classList.toggle('active',x===b));renderTasks()});
$('#photoBtn').addEventListener('click',()=>$('#photoInput').click());$('#photoInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{setPhoto(await compressImage(f));toast('Foto de Torti actualizada')}catch{toast('No pude procesar esa foto')}});
$('#exportBtn').addEventListener('click',()=>{const payload={version:2,exported:new Date().toISOString(),state,photo:localStorage.getItem(PHOTO)||null,theme:localStorage.getItem(THEME)||'light'};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`torti-respaldo-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Respaldo creado')});
$('#importBtn').addEventListener('click',()=>$('#importInput').click());$('#importInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!p.state||!Array.isArray(p.state.records))throw 0;state.records=p.state.records;state.checks=p.state.checks||{};state.tasks=p.state.tasks||[];if(p.photo)setPhoto(p.photo);save();toast('Respaldo restaurado')}catch{toast('Ese archivo no es un respaldo válido')}};r.readAsText(f)});
$('#clearBtn').addEventListener('click',()=>{if(confirm('¿Borrar todos los registros y tareas de Torti de este dispositivo?')){state.records=[];state.checks={};state.tasks=[];localStorage.setItem(KEY,JSON.stringify(state));render();toast('Datos eliminados')}});
$('#printBtn').addEventListener('click',()=>window.print());
const dark=localStorage.getItem(THEME)==='dark';document.body.classList.toggle('dark',dark);$('#darkToggle').checked=dark;$('#darkToggle').addEventListener('change',e=>{document.body.classList.toggle('dark',e.target.checked);localStorage.setItem(THEME,e.target.checked?'dark':'light')});
applyPhoto(localStorage.getItem(PHOTO));render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});